### ISSUE TITLE
Dependency Analyzer doesn't ignore dependencies from <dependencyManagement>

### ISSUE THREAD

**Issue by holub** [krasa/MavenHelper#11] opened 2016-02-09 14:49 UTC
Together with module dependencies "Dependency Analyzer" tab shows dependencies provided in the
`<project><dependencyManagement><dependencies>`section. These dependencies are not always the actual dependencies of the module.
They become real dependencies only after declaration in `<project><dependencies>` section.

**Comment by krasa** [comment] 2016-02-09 16:34
Works fine for me in IJ 16 EAP:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ff</groupId>
    <artifactId>gfg</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.0.1</version>
        </dependency>
    </dependencies>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.9</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


</project>
```
shows only **logback-core**

**Comment by holub** [comment] 2016-02-09 16:39
Thank you for the fast response!
My configuration is a little bit more complicated. The **dependencyManager** section is taken from parent pom. Maybe that's the case?

**Comment by krasa** [comment] 2016-02-09 17:10
Tried that, everything works fine for me.

**Comment by holub** [comment] 2016-02-09 17:13
Don't close the issue for few days. I'll try to reproduce the issue in minimalistic environment and let you know.

**Comment by krasa** [comment] 2016-02-09 17:15
ok

**Comment by holub** [comment] 2016-02-10 16:14
I can't create minimal configuration, but the issue is here.
1. I see unexpected dependencies in module M1 (packaging:pom)
2. Remove everything from pom except `<parent>` section
3. Still see the jars. Expecting have this dependencies somewhere in parent P1 (packaging:pom).
4. Checking parent: it doesn't show this dependencies. :(

Sometimes I can see dependencies in P1 but that's rare case.
Bottom line: can't find way to reproduce the issue.

**Comment by krasa** [comment] 2016-02-10 16:50
The problem is probably in IntelliJ or Maven itself - which IJ uses for resolving dependencies. This plugin only takes cached data from IntelliJ. 
If you could see the same behaviour in the project settings, when you display module dependencies, then reporting IJ bug would be the best.

**Comment by holub** [comment] 2016-02-10 17:38
Thank you. I'll keep eye on it.

**Comment by krasa** [comment] 2016-03-03 10:07
https://youtrack.jetbrains.com/issue/IDEA-133331#comment=27-1323737

**Closed** 2016-06-08 15:01 UTC
